GCP_ETE:
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: fair-gist-467212-e2
      dataset: ny_taxi_proccessed
      threads: 1
      timeout_seconds: 300
      location: US
  target: dev
